### ISSUE TITLE
Sender MissingAuthenticationToken

### ISSUE THREAD

**Issue by Foap** [joelcox/codeigniter-amazon-ses#15]
Hello,

I get this error when I try to send an email.

Sender MissingAuthenticationToken

This is my CI code.

$this->load->library('amazon_ses');
$this->amazon_ses->to('example@gmail.com');
$this->amazon_ses->subject('Open me!');
$this->amazon_ses->message('<strong>Use HTML</strong>');

$this->amazon_ses->debug(TRUE);
print_r( $this->amazon_ses->send() );

What can be wrong? I have entered my AWS credentials in the config file.

**Comment by joelcox** [comment]
Hi Foap,

Are you using the most recent version of this library? Could you check what the value of the `headers` property is in the `Curl` class? My gut feeling is that this error has to do with `hash_hmac()`.

**Comment by Foap** [comment]
Yeah, you were right. I updated the Curl file with latest version and now it works! Thanks for a great library!

**Comment by joelcox** [comment]
Thanks. Great you got it working.
