### ISSUE TITLE
Contradicting Email Validation

### ISSUE THREAD

**Issue by brwnll** [joelcox/codeigniter-amazon-ses#16]
Is there a reason why this would be happening?

```
echo $this->amazon_ses->address_is_verified('support@smalldo.gs') ? 'Verified' : 'Not verified';

$this->amazon_ses->to('me@gmail.com');
$this->amazon_ses->from('support@smalldo.gs');
$this->amazon_ses->subject('Open me!');
$this->amazon_ses->message('<strong>Use HTML</strong>');
$this->amazon_ses->debug(TRUE);

print_r( $this->amazon_ses->send() );
```

Output
`Verified` then `Sender MessageRejected Email address is not verified. 64caaa79-4c55-11e1-924f-635e9ccede3d`

I received the validation email and Amazon said it had been successfully validated.

**Comment by joelcox** [comment]
Hi Dustin, 

Looks like I messed up with the return value of address_is_verified(). Could you post the output of `var_dump($this->amazon_ses->address_is_verified('support@smalldo.gs')` here? I do not have any problems with verifying email addresses though.

Also make sure that the to address is verified if you haven't been granted production access yet.

> If you are a new Amazon SES user and have not yet received production access to Amazon SES, then you can only send email to addresses that you have previously verified. To view your list of verified email addresses, go to the AWS Management Console or refer to the Amazon SES Developer Guide.

**Comment by brwnll** [comment]
Ah. My mistake. It was the issue with not being moved to production yet. Thanks.
