### ISSUE TITLE
SignatureDoesNotMatch error

### ISSUE THREAD

**Issue by ricick** [joelcox/codeigniter-amazon-ses#17]
I am running into the following error.

```
The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and 
signing method. Consult the service documentation for details.
```

I'm assuming it relates to the amazon_ses_secret_key and amazon_ses_access_key which I copied from the created smtp user in the ses page. Did I get this right?

Any help would be appreciated.

**Comment by joelcox** [comment]
Hi ricick, you can obtain these keys through the process outlined [here](http://docs.amazonwebservices.com/ses/latest/GettingStartedGuide/GetAccessIDs.html). I believe the SMTP access keys differ from the global access keys.

**Comment by joelcox** [comment]
Hi ricick, did you manage to get things working?

**Comment by ricick** [comment]
Hi Joel. That fixed it thanks. I was using the keys provided by the "create smtp credentials" workflow under the ses control panel.

Maybe the config parameters should be renamed from "amazon_ses_access_key" to "amazon_aws_access_key" to make it more obvious.

**Comment by joelcox** [comment]
Glad you got things working. The `amazon_ses` prefix is purely for namespacing the config parameters. Since this library was developed before AWS rolled out SMTP support for SES, I didn't foresee this mix up. I'll add an extra link in the documentation on how to obtain these keys. :)
