### ISSUE TITLE
Batch send

### ISSUE THREAD

**Issue by dkrusenstrahle** [joelcox/codeigniter-amazon-ses#20]
Hello!

Is there a way to send a batch of emails instead of one by one?
It talkes a very long time to loop through and send email from an array one by one.

Thanks!

**Comment by joelcox** [comment]
Hi dkrusenstrahle,

Sorry for my late response, I was away from my computer for most of today and yesterday. As far as I know, Amazon SES doesn't have an API method which allows your to send batch emails. Most of the overhead you're getting is probably from the HTTP request to their API, so there isn't much you can do about that, other than making sure you have a good connection with Amazon US1 zone.

**Comment by dkrusenstrahle** [comment]
Hi Joelcox,

No problem! I think I may have found why it is so slow. In my library file I have set the default region to us-east-1. I think I am using the datacenter in Ireland. Do you know the region name for that?

Thanks!

**Comment by joelcox** [comment]
Heya. Sadly Amazon SES is only available at `us-east-1`. See http://aws.amazon.com/ses/faqs/#6
