### ISSUE TITLE
adding the chartset ?

### ISSUE THREAD

**Issue by imknight** [joelcox/codeigniter-amazon-ses#3]
added these for function format_query_string ? and initiate the chartset 

<code>
'Message.Body.Html.Charset' => $this->chartset;

'Message.Body.Text.Charset' => $this->chartset;

'Message.Subject.Charset' => $this->chartset;
</code>

**Comment by joelcox** [comment]
Yep, this should be included!

EDIT: Woops, shouldn't have closed that.
