### ISSUE TITLE
function from takes $name as argument but does nothing with it

### ISSUE THREAD

**Issue by nickdavies** [joelcox/codeigniter-amazon-ses#6]
Hey, just letting you know that you have $name = NULL on line 107 but that is the only reference to it. 

I have looked at the API spec and this value isn't a parameter. Please Comment somewhere either in the readme or in the library that this does not actually have any effect.

Regards,
Nick

**Comment by joelcox** [comment]
Thanks for reporting this! I actually implemented this hoping that Amazon would add this someday... I'll remove the parameter for now.

Joël

**Comment by joelcox** [comment]
Apparently, this is possible!

https://forums.aws.amazon.com/message.jspa?messageID=218579
